### ISSUE TITLE
some borders and lines?

### ISSUE THREAD

**Issue by intervisionlord** [cactushead/cactus-light-theme#1]
Without line separation it looks like strange isn't it?
Please add some...

[![f8f0af593f58ad5d01e1d8e48592d264.md.png](https://dropimg.ru/images/2019/11/09/f8f0af593f58ad5d01e1d8e48592d264.md.png)](https://dropimg.ru/images/2019/11/09/f8f0af593f58ad5d01e1d8e48592d264.png)

**Comment by cactushead** [comment]
Thank you for your input.
I have updated the theme to better differentiate the headers by adding a border, background color and a bit of spacing.
I hope this makes things a bit easier for you.

**Comment by intervisionlord** [comment]
thanks a lot! you are awesome )

**Comment by cactushead** [comment]
No problem
